import { z } from "zod";

export const ImovelSchema = z.object({
  titulo: z.string().optional(),
  descricao: z.string().nullable().optional(),
  subtipo_id: z.number().optional(),
  tipoimovel_id: z.number().optional(),
  preco: z.number().optional(),
  area: z.number().nullable().optional(),
  quartos: z.number().nullable().optional(),
  banheiros: z.number().nullable().optional(),
  vagas_garagem: z.number().nullable().optional(),
  endereco: z.string().optional(),
  numero: z.string().nullable().optional(),
  complemento: z.string().nullable().optional(),
  bairro: z.string().optional(),
  cidade: z.string().optional(),
  estado: z.string().optional(),
  estado_id: z.number().nullable().optional(),
  cep: z.string().nullable().optional(),
  latitude: z.number().nullable().optional(),
  longitude: z.number().nullable().optional(),
  data_cadastro: z.coerce.date().nullable().optional(),
  data_atualizacao: z.coerce.date().nullable().optional(),
  disponivel: z.boolean().nullable().optional(),
  destaque: z.boolean().nullable().optional(),
  imagens: z.array(z.string()).optional(),
  id_proprietario: z.number().nullable().optional(),
  id_corretor: z.number().nullable().optional(),
  area_util_hectares: z.number().nullable().optional(),
  area_total_hectares: z.number().nullable().optional(),
  salas: z.number().nullable().optional(),
  andar: z.number().nullable().optional(),
  area_privativa: z.number().nullable().optional(),
  area_comum: z.number().nullable().optional(),
  suites: z.number().nullable().optional(),
  mobiliado: z.boolean().nullable().optional(),
  aceita_animais: z.boolean().nullable().optional(),
  views: z.number().nullable().optional(),
  valor_iptu: z.number().nullable().optional(),
  valor_condominio: z.number().nullable().optional(),
});