export interface Moveis {
    id: number,
    titulo: string,
    descricao: string,
    subtipo_id: number,
    tipoimovel_id: number,
    preco: number,
    area: number,
    quartos: number,
    banheiros: number,
    vagas_garagem: number,
    endereco: string,
    numero: string | null,
    complemento: string | null,
    bairro: string,
    cidade: string,
    estado: string,
    estado_id: number,
    cep: string,
    latitude: number,
    longitude: number,
    data_cadastro?: Date,
    data_atualizacao?: Date
    disponivel: boolean,
    destaque: boolean,
    id_proprietario?: number,
    area_util_hectares?: number,
    area_total_hectares?: number
    salas: number,
    andares?: number,
    area_privativa?: number,
    area_comum?: number,
    suites?: number,
    mobiliado?: boolean,
    aceita_animais?: boolean,
    views?: number,
    valor_iptu?: number,
    valor_condominio?: number
}